[package]
org = "ballerinax"
name = "health.fhir.r4.validator"
version = "1.0.0"
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Validator"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
export = ["health.fhir.r4.validator"]

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "3.0.1"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.parser"
version = "1.0.0"
