[package]
org = "ballerinax"
name = "health.fhir.r4utils.ccdatofhir"
version = "1.0.0"
distribution = "2201.6.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "R4", "Utils", "CCDAtoFHIR"]
export = ["health.fhir.r4utils.ccdatofhir"]
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.r4"
